[package]
name = "akari"
version = "0.1.0"
authors = ["lcnr/Bastian Kauschke <bastian_kauschke@hotmail.de>"]
edition = "2018"

[dependencies.amethyst]
version = "0.11"
features = ["vulkan", "nightly"]